name: Merge changes

on: 
  push:
    branches: [master]
  pull_request: 
    branches: [master]
    types: [opened, synchronize]

jobs:
  
  redundancy:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node_version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
          
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node_version: 16
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test  
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
